### ISSUE TITLE
GQA aligned triplets is not aligned with GQA GT data

### ISSUE THREAD

**Issue by NimrodShabtay** [rlqja1107/torch-LLM4SGG#1]
Hi,
Thank you for amazing and interesting work!

I am working with GQA and I want to use the provided aligned triplets, how ever I cannot match the image ids from the provided file in the readme to any GT graphs in GQA validation or training set.
Can you assist?

Thanks,
Nimrod

**Comment by rlqja1107** [comment]
Thank you for your interest in my work!

It appears there might be some confusion. 
To assess our model's performance on the GQA dataset, we utilize the COCO caption dataset for training, rather than relying on GT graph in GQA dataset. To be more precise, we extract triplets from the COCO caption dataset and ensure that the entity and predicate classes align with those found in the GQA dataset. Once the model is trained with aligned triplets, we then assess its performance on the GQA test dataset.

For weakly supervised scene graph generation task, we only utilize captions alongside their corresponding images, instead of relying on the GT graph provided in the GQA dataset.

I hope this aids in your comprehension.

Thank you!
Kibum Kim

**Comment by NimrodShabtay** [comment]
Thanks @rlqja1107 for the quick response and the clarification.
If that's the case my question will be, from the outputs you've shared in this project, how can I extract pairs of images (or image_ids from GQA) and the corresponded graphs you've generated?
I am not sure how to link the generated graphs to GQA image_ids.

Thank you,
Nimrod

**Comment by rlqja1107** [comment]
I think my previous response doesn't fully make you understand the process.
For evaluation on GQA dataset, we don't use scene graph dataset i've generated, which is obtained from COCO caption dataset.
Instead, we use the ground-truth localized scene graph dataset provided in the *GQA_200_Test.json* file in order to assess the model's performance. This file can be downloaded from link shown in below figure.

![image](https://github.com/rlqja1107/torch-LLM4SGG/assets/55014424/331e6413-ace7-4fec-ba72-4188db9fe010)

For better understanding, 
Train → scene graph i've generated in COCO caption (image id corresponds to COCO)
Test → GQA (image id corresponds to GQA)

Therefore, the graphs that I've generated cannot be aligned with the image id in the GQA dataset.
Is there still any confusion remaining after reading this response?
Feel free to ask anything if you have any questions or need further clarification.

Thank you,
Kibum Kim
