### ISSUE TITLE
GLIP version

### ISSUE THREAD

**Issue by ZHUXUHAN** [rlqja1107/torch-LLM4SGG#10]
Dear author, may I ask if the GLIP model you used is the Tiny version? If so, could you kindly provide the experimental results on the COCO->VG test using the Large version of the model? I would greatly appreciate it.

**Comment by rlqja1107** [comment]
Thank you for your interest!

In the overall experiment, we used the Tiny version of GLIP. Unfortunately, there are no separate results from experiments conducted with the Large version of GLIP.

Instead, performing the COCO->VG test with the GLIP Large version is easy, as it only requires changing the GLIP version. You can easily download the GLIP with a large version from the following link: https://github.com/microsoft/GLIP#model-zoo

Thank you.

**Comment by ZHUXUHAN** [comment]
Regarding the reproduction of the Large version, we need to compare it with your method, so we need the language_supervised-coco_caption-grounding=glipL-javaparser.json file, which comes from VS3. You should have it, and in order to compare with your reproduction version, could you provide the file you used?

**Comment by ZHUXUHAN** [comment]
Hi, dear sir, we find the VS3 use the VG test data split is 'split_GLIPunseen', do you use this data split to test your models?

**Comment by rlqja1107** [comment]
Thank you for your comment.

Yes, I use the same data split as VS3. As shown in the figure below, I indicate that I follow the same data preprocessing as VS3.
![image](https://github.com/user-attachments/assets/19f53ad4-f0b2-4731-aa23-6840b2e50538)

Additionally, if you run the test code, you'll easily find that the total number of test images is 14.7K, rather than the original test set size of 23K.

**Comment by ZHUXUHAN** [comment]
OK, for the GQA-200, do you use the original test split data?

**Comment by rlqja1107** [comment]
Yes, i use the original test split data for the GQA-200.

**Comment by ZHUXUHAN** [comment]
Ok, thank you very much.
